<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/**
 * @see \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer
 */
/** @var $block \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer */
?>


<?php $parentItem = $block->getItem();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$bundleProduct = $objectManager->create('Magento\Catalog\Model\Product')->load($parentItem->getProductId());
$orderItemInterface = $objectManager->create('\Magento\Sales\Api\OrderItemRepositoryInterface');

$items = $block->getChildren($block->getItem());
$_count = count($items);
$_index = 0;

$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
$_prevOptionId = '';
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$advanceBundleHelper = $this->helper('Cellularisrael\BundleProduct\Helper\Data');
 ?>


<?php foreach ($items as $_item):             
    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getProductId());   
    $orderItemData = $orderItemInterface->get($_item->getOrderItemId());        
    if($orderItemData->getProductType() == "bundle"){
        continue;
    }

    $currencyString = "USD";    
    if($orderItemData->getStoreId() == 3 || $orderItemData->getStoreId() == 4){
        $currencyString = "ILS";
    }

    $provider = "By Cellular Israel";
    if($orderItemData->getMerchant() ==  2){
        $provider = "By Provider";
    }
    
    if($orderItemData->getIsPlan()){ ?>
        <tr class="planned-product">
            <td class="col item">
                <div class="product-item-image">                    
                    <a href="<?= $block->escapeUrl($bundleProduct->getProductUrl()) ?>"
                           title="<?= $block->escapeHtml($orderItemData->getProductName()) ?>"
                           tabindex="-1"
                           class="product-item-photo">                    
                        <?php                        
                        $image_url = $imageHelper->getDefaultPlaceholderUrl('small_image');
                        if($bundleProduct && $bundleProduct->getSmallImage()){
                            $image_url = $imageHelper->init($bundleProduct, 'small_image')->setImageFile($bundleProduct->getSmallImage())->resize(200,200)->getUrl();    
                        }
                        ?>
                        <span class="product-image-container">
                            <span class="product-image-wrapper">
                                <img class="product-image-photo" src="<?= $image_url ?>" />        
                            </span>
                        </span>
                    </a>                    
                </div>
                <div class="product-item-details">
                    <div class="product-important-detail">              
                        <strong class="product-item-name">                            
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </strong> 
                        <div class="product-selected-time">
                            <div class="active-time">
                                <span class="label"><?= __('Start date'); ?></span>
                                <span class="content"><?= $advanceBundleHelper->getFormatedDate($orderItemData->getStartDate()); ?></span>
                            </div>
                            <div class="active-time">
                                <span class="label"><?= __('End date'); ?></span>
                                <span class="content"><?= $advanceBundleHelper->getFormatedDate($orderItemData->getEndDate()); ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="cart-input-sec">                       
                            <div class="field qty">
                                <label><span class="label"><?= $block->escapeHtml(__('Quantity')) ?></span></label>
                                <label><span class="label"><?= $_item->getQty() * 1;  ?></span></label>
                            </div>
                        </div>
                </div>       
            </td> 
            
            <?php if($orderItemData->getIsSubscription()): ?>
                <td class="col price onetime">
                    &nbsp;
                </td>

                <td class="col price monthly">
                    <?php if (strpos($provider, 'Provider') !== false && $orderItemData->getIsraelPrice()) { ?>
                        <span class="currency-symbol"><?= $advanceBundleHelper->getCurrencySymbol('ILS'); ?></span><?= number_format(($orderItemData->getIsraelPrice() * $_item->getQty()),2); ?>
                        <span class="merchant"><?= __($provider) ?></span>
                    <?php }else{ ?>
                        <span class="currency-symbol"><?= $advanceBundleHelper->getCurrencySymbol($currencyString); ?></span><?= number_format(($orderItemData->getPrice() * $_item->getQty()),2); ?>   
                        <span class="merchant"><?= __($provider) ?></span>
                        <?php } ?>
                    
                </td>

            <?php else: ?>
                <td class="col price onetime">
                    <?php if (strpos($provider, 'Provider') !== false && $orderItemData->getIsraelPrice()) { ?>
                        <span class="currency-symbol"><?= $advanceBundleHelper->getCurrencySymbol('ILS'); ?></span><?= number_format(($orderItemData->getIsraelPrice() * $_item->getQty()),2); ?>
                        <span class="merchant"><?= __($provider) ?></span>
                    <?php }else{ ?>
                        <span class="currency-symbol"><?= $advanceBundleHelper->getCurrencySymbol($currencyString); ?></span><?= number_format(($orderItemData->getPrice() * $_item->getQty()),2); ?>   
                        <span class="merchant"><?= __($provider) ?></span>
                        <?php } ?>
                </td>
                <td class="col price monthly">
                    &nbsp;
                </td>
            <?php endif; ?>
        </tr>

    <?php }else{ ?>
        <tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>" class="<?php if ($_item->getParentItem()): ?>item-options-container<?php else: ?>item-options-container<?php endif; ?>">
            <td class="col item">
                <div class="product-item-image">            
                <span class="product-item-photo">            
                    <?php
                    $image_url = $imageHelper->getDefaultPlaceholderUrl('small_image');
                    if($product && $product->getSmallImage()){
                        $image_url = $imageHelper->init($product, 'small_image')->setImageFile($product->getSmallImage())->resize(200,200)->getUrl();    
                    }                                         
                    ?>
                    <span class="product-image-container">
                        <span class="product-image-wrapper">
                            <img class="product-image-photo" src="<?= $image_url ?>" />        
                        </span>
                    </span>            
                </span>            
                </div>
                <div class="product-item-details">
                    <div class="product-important-detail">              
                        <strong class="product-item-name">                   
                            <?= $block->escapeHtml($_item->getName()) ?>                    
                        </strong>                 
                    </div>            
                </div>
            </td> 
            
            <?php if($orderItemData->getIsSubscription()): ?>
                <td class="col price onetime">
                    &nbsp;
                </td>

                <td class="col price monthly">
                    <?php if (strpos($provider, 'Provider') !== false) { ?>
                        <span class="currency-symbol"><?= $advanceBundleHelper->getCurrencySymbol('ILS'); ?></span><?= number_format(($orderItemData->getIsraelPrice() * $_item->getQty()),2); ?>
                        <span class="merchant"><?= __($provider) ?></span>
                    <?php }else{ ?>
                        <span class="currency-symbol"><?= $advanceBundleHelper->getCurrencySymbol($currencyString); ?></span><?= number_format(($orderItemData->getPrice() * $_item->getQty()),2); ?>   
                        <span class="merchant"><?= __($provider) ?></span>
                        <?php } ?>
                </td>

            <?php else: ?>
                <td class="col price onetime">
                    <?php if (strpos($provider, 'Provider') !== false && $orderItemData->getIsraelPrice()) { ?>
                        <span class="currency-symbol"><?= $advanceBundleHelper->getCurrencySymbol('ILS'); ?></span><?= number_format(($orderItemData->getIsraelPrice() * $_item->getQty()),2); ?>
                        <span class="merchant"><?= __($provider) ?></span>
                    <?php }else{ ?>
                        <span class="currency-symbol"><?= $advanceBundleHelper->getCurrencySymbol($currencyString); ?></span><?= number_format(($orderItemData->getPrice() * $_item->getQty()),2); ?>   
                        <span class="merchant"><?= __($provider) ?></span>
                        <?php } ?>                
                </td>
                <td class="col price monthly">
                    &nbsp;
                </td>
            <?php endif; ?>
        </tr>
    <?php } ?>    
<?php endforeach; ?>
