<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Sales\Block\Adminhtml\Order\View\History $block */
?>
<div id="order_history_block" class="edit-order-comments">
    <?php if ($block->canAddComment()):?>
        <div class="order-history-block" id="history_form">

            <div class="admin__field">
                <label for="history_status" class="admin__field-label"><?= /* @noEscape */ __('Status') ?></label>
                <div class="admin__field-control">
                    <select name="history[status]" id="history_status" class="admin__control-select">
                        <?php foreach ($block->getStatuses() as $_code => $_label): ?>
                            <option value="<?= $block->escapeHtml($_code) ?>"<?php if ($_code == $block->getOrder()->getStatus()): ?> selected="selected"<?php endif; ?>><?= $block->escapeHtml($_label) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="admin__field">
                <label for="history_comment" class="admin__field-label">
                    <?= /* @noEscape */ __('Comment') ?>
                </label>
                <div class="admin__field-control">
                    <textarea name="history[comment]"
                              rows="3"
                              cols="5"
                              id="history_comment"
                              class="admin__control-textarea"></textarea>
                </div>
            </div>

            <div class="admin__field">
                <div class="order-history-comments-options">
                    <div class="admin__field admin__field-option">
                        <?php if ($block->canSendCommentEmail()): ?>
                            <input name="history[is_customer_notified]"
                                   type="checkbox"
                                   id="history_notify"
                                   class="admin__control-checkbox"
                                   value="1" />
                            <label class="admin__field-label" for="history_notify">
                                <?= /* @noEscape */ __('Notify Customer by Email') ?>
                            </label>
                        <?php endif; ?>
                    </div>

                    <div class="admin__field admin__field-option inline-display">
                        <input name="history[is_visible_on_front]"
                               type="checkbox"
                               id="history_visible"
                               class="admin__control-checkbox"
                               value="1" />
                        <label class="admin__field-label" for="history_visible">
                            <?= /* @noEscape */ __('Visible on Storefront') ?>
                        </label>
                    </div>
                    <div class="admin__field admin__field-option inline-display">
                        <input name="history[is_order_important_note]"
                               type="checkbox"
                               id="is_order_important_note"
                               class="admin__control-checkbox"
                               value="0" />
                        <label class="admin__field-label" for="is_order_important_note">
                            <?= /* @noEscape */ __('Important Note') ?>
                        </label>
                    </div>
                </div>

                <div class="order-history-comments-actions">
                    <?= $block->getChildHtml('submit_button') ?>
                </div>
            </div>
        </div>
    <?php endif;?>
    <?php   
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
        // $baseUrl = $storeManager->getStore()->getBaseUrl();
        // Get Main website base url
        $mainWebsite = $storeManager->getWebsite('base');
        $baseUrl = $mainWebsite->getDefaultStore()->getBaseUrl();
        $adminUsers = $objectManager->create('\Magento\User\Model\ResourceModel\User\Collection');
    ?>
    <div class="custom-order-comment-filter">
        <form>
            <div class="order-history-form">
                <div class="admin__field">
                    <label for="order_by" class="admin__field-label">Sort by Date</label>
                    <div class="admin__field-control">
                        <select name="order_by" id="order_by" class="admin__control-select">
                          <option value="">Select Sort By</option>
                          <option value="DESC">DESC</option>
                          <option value="ASC">ASC</option>
                        </select>
                    </div>
                </div>
                <div class="admin__field">
                    <label for="user" class="admin__field-label">Select User</label>
                    <div class="admin__field-control">
                        <select name="user" id="user" class="admin__control-select">
                            <option value="">Select User</option>
                            <option value="All">All</option>
                            <?php foreach ($adminUsers as $admin): ?>
                                <option value="<?php echo $admin->getUserId() ?>"><?php echo $admin->getUSername() ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>                
                </div>             
            </div>             
        </form>
    </div>
    <div class="custom-order-comment"><b>please select above option to see order history</b></div>

<script type="text/javascript">
require([
'jquery'
], function($){
        $(document).ready(function(){
            var order_id = '<?php echo $block->getOrder()->getId(); ?>';
            var order_by = '';
            var user = '';
            var url = '<?php echo $baseUrl; ?>';
            getStatusHisroty(url,order_by, order_id, user);

            $('#is_order_important_note').change(function() {
                if(this.checked) {
                    $(this).prop("checked", true);
                    $(this).val("1");
                } else {
                    $(this).val("0");
                }
            });
            
            $(document).on("change", '#order_by,#user', function() {
                var order_by = $( "#order_by option:selected" ).val();
                var user = $( "#user option:selected" ).val();
                getStatusHisroty(url,order_by, order_id, user);
            });
        });

        function getStatusHisroty(url,order_by, order_id, user) {
            $.ajax({
                url: url + 'poorder/index/comment',
                type: 'post',
                showLoader: true,
                data: {
                    'order_by' : order_by,
                    'order_id' : order_id,
                    'user' : user,
                },
                success: function(response){
                    $(".custom-order-comment").html(response);
                }
            });
        }
});
</script>
<script>
    require(['prototype'], function(){

            if($('order_status'))$('order_status').update('<?= $block->escapeJs($block->escapeHtml($block->getOrder()->getStatusLabel())) ?>');

    });
</script>
</div>
