<?php
//@codingStandardsIgnoreFile
/** @var \Mirasvit\Search\Block\Index\Base $block */
?>
<div class="mst-search__index mst-search__index-external-wordpress-post">
    <?= $block->getPager() ?>
    <ul>
        <?php /** @var \Mirasvit\Blog\Model\Post $post */ ?>
        <?php foreach ($block->getCollection() as $post): ?>
            <li>
                <div class="mst-search__index-title">
                    <a href="<?= $post->getUrl() ?>"><?= $post->getName() ?></a>
                </div>

                <div class="mst-search__index-content">
                    <?= $this->truncate($block->stripTags($post->getShortContent() ? $post->getShortContent() : $post->getContent())) ?>
                </div>

                <a style="float: right" href="<?= $post->getUrl() ?>"><?= __('Read more...') ?></a>
            </li>
        <?php endforeach ?>
    </ul>
    <?= $block->getPager() ?>
</div>

